apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-cource-vdb
  labels:
    app: dotnet-cource-vdb
    kubernetes.azure.com/generator: devhub
  namespace: demo-aks-cource
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-cource-vdb
  template:
    metadata:
      labels:
        app: dotnet-cource-vdb
    spec:
      containers:
        - name: dotnet-cource-vdb
          image: vdbregistry.azurecr.io/demo-vdb-1719380332263:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
